### ISSUE TITLE
Cannot build because of "undefined: allPackages"

### ISSUE THREAD

**Issue by toliaqat** [kisielk/gotool#12]
Recent commit broke building this tool and other tools depending (kisielk/errcheck) on it.

Repro:
```
$ go get -u github.com/kisielk/gotool
# github.com/kisielk/gotool
../../kisielk/gotool/match.go:158: undefined: allPackages
../../kisielk/gotool/match.go:266: undefined: c in c.BuildContext
../../kisielk/gotool/match.go:268: undefined: log in log.Print```

**Comment by shurcooL** [comment]
#12 fixes this issue.

See messages in https://github.com/kisielk/gotool/pull/8#issuecomment-231557675.

Waiting on @kisielk to review and merge #12, hopefully soon.
