### ISSUE TITLE
Adapt to tip's ignoring of /vendor/ in ...

### ISSUE THREAD

**Issue by mvdan** [kisielk/gotool#16]
See https://github.com/golang/go/issues/19090.

I guess `gotool` could either always ignore vendor, or only on 1.9 and above. Not sure whether the library prefers consistency with itself or with Go's `cmd/go`.

**Comment by kisielk** [comment]
I think it would be fine to include it for all versions of gotool.

**Comment by mvdan** [comment]
A point in favor of that is that programs using `gotool` could get rid of the `grep -v /vendor/` stuff from their READMEs, regardless of what Go versions people use the programs with.

**Comment by kisielk** [comment]
Definitely. Do you want to prepare a PR?

**Comment by mvdan** [comment]
Sure, I'll give it a go. Quick question - do you guys plan on adapting to the new multi-package structure of `cmd/go`, or should I backport Russ's commit to this single-package structure?

**Comment by kisielk** [comment]
Honestly I don't really have any plans either way yet :) I haven't really looked into the cmd/go changes in depth, but if the basic components have been split up into multiple packages it may be easier to just go with what they've done to make it easier to port over future changes.

**Comment by shurcooL** [comment]
Agree, I think it's best for us to aim to have the smallest diff between our code and upstream code. Our code should effectively be a subset of `cmd/go/...` code, and an exported API that exposes it.

If the multiple package structure looks messy, it might be worth "hiding" it under `/internal/` import path element.

**Comment by kisielk** [comment]
I agree it would be best to have just one public package but I'm fine splitting up the rest into internals

**Comment by mvdan** [comment]
I agree with smallest diffs possible. In that case, this project is bigger than just backporting a small commit :) Will let someone else do it, since the reorganization should happen before the vendor change.

**Comment by bradleyfalzon** [comment]
> Sure, I'll give it a go. Quick question - do you guys plan on adapting to the new multi-package structure of cmd/go, or should I backport Russ's commit to this single-package structure?

Can someone clarify exactly what's meant by this? Specifically the `multi-package structure of cmd/go`. Perhaps there's some history here that I don't completely understand?

**Comment by kisielk** [comment]
Check out the directory structure of https://github.com/golang/go/tree/master/src/cmd/go, particularly in `internal/`

**Comment by bradleyfalzon** [comment]
Yeah, I had, as that's what I thought we were referring to, but then there's files such as https://github.com/golang/go/blob/master/src/cmd/go/internal/version/version.go which I wouldn't have thought gotool was concerned with?

**Comment by kisielk** [comment]
We certainly don't want everything from `cmd/go/...` but generally want to keep current with how the code is laid out. For exampe the vendor path stuff is moved to `cmd/go/internal/load` so we'd probably want to have `github.com/kisielk/gotool/internal/load` to mirror that structure.

**Comment by dominikh** [comment]
> A point in favor of that is that programs using gotool could get rid of the grep -v /vendor/ stuff from their READMEs, regardless of what Go versions people use the programs with.

That doesn't sound like a point in favor. The whole purpose of gotool is to allow tools to have the same behaviour as the go tool. Ergo we should maintain the old behaviour for Go 1.8, and only use it in 1.9 and onwards.

**Comment by shurcooL** [comment]
I'll be able to work on resolving this later today or tomorrow, if no one else gets to it before then.

**Comment by shurcooL** [comment]
I understand we'll want to make it so that `gotool.ImportPaths` can be safely called by multiple goroutines. If that weren't the case, I could get away with a smaller diff.

**Comment by shurcooL** [comment]
Made good progress on this. I have a working prototype. I need to evaluate my current approach against alternatives and find the best solution that'll be easiest to maintain in the future, and easiest to be confident in its correctness. Gotta do other stuff now, but will resume working on this in the evening.

**Comment by bradleyfalzon** [comment]
I don't see why we'd need to make it safe to be called from multiple goroutines to be honest. Seems like something that's called once during program execution, the only case I can think of off the top of my head is in tests. But perhaps there's other use cases I haven't thought of.

If it helps, I can look through some of the usages to check?

**Comment by dominikh** [comment]
I don't see why it *shouldn't* be safe to call from multiple goroutines. From the API surface, it looks like a read-only operation. I also believe that the current API is safe for concurrent use, so changing that would break existing contracts.

**Comment by shurcooL** [comment]
It's easier to just make it safe for concurrent use than anything else. I just wanted to point out that doing so will have a slight increase of maintenance cost because it necessitates a larger diff against upstream.

**Comment by shurcooL** [comment]
A question that comes up is what to do about GOROOT detection. In Go 1.8, `go list` was doing:

```Go
var goroot = filepath.Clean(runtime.GOROOT())
```

([Source](https://gotools.org/cmd/go?rev=go1.8.3#build.go-L780).)

In Go 1.9, `go list` command does extra things to find GOROOT:

```Go
func findGOROOT() string {
	if env := os.Getenv("GOROOT"); env != "" {
		return filepath.Clean(env)
	}
	exe, err := os.Executable()
	if err == nil {
		exe, err = filepath.Abs(exe)
		if err == nil {
			if dir := filepath.Join(exe, "../.."); isGOROOT(dir) {
				return dir
			}
			exe, err = filepath.EvalSymlinks(exe)
			if err == nil {
				if dir := filepath.Join(exe, "../.."); isGOROOT(dir) {
					return dir
				}
			}
		}
	}
	return filepath.Clean(runtime.GOROOT())
}

// isGOROOT reports whether path looks like a GOROOT.
//
// It does this by looking for the path/pkg/tool directory,
// which is necessary for useful operation of the cmd/go tool,
// and is not typically present in a GOPATH.
func isGOROOT(path string) bool {
	stat, err := os.Stat(filepath.Join(path, "pkg", "tool"))
	if err != nil {
		return false
	}
	return stat.IsDir()
}
```

([Source](https://gotools.org/cmd/go/internal/cfg?rev=go1.9#cfg.go-L97-L130).)

We cannot copy that logic outright. The logic depends on the fact that the `go` binary is located in GOROOT at GOROOT/bin/go. A binary that uses `gotool` package will most likely not be inside GOROOT.

I see two alternatives:

1. Just keep relying on `runtime.GOROOT()` for now.
2. Modify the above logic but look for `go` binary via [`exec.LookPath`](https://godoc.org/os/exec#LookPath) instead of using `os.Executable`.

I'm planning to go with solution 1 for now... 2 seems to be overly complex and I'm not sure if it brings any benefits. It might be worse. I think we should discuss it separately before considering implementing it.

**Comment by shurcooL** [comment]
Also, it feels weird that `cmd/go` is not using `build.Context.GOROOT`... I wonder if there's a good reason for that.

**Comment by shurcooL** [comment]
It feels pretty suboptimal to me and I think there's an opportunity to simplify code (upstream).

Consider, this is the only place where `gorootSrc` is used:

```Go
for _, src := range c.BuildContext.SrcDirs() {
	if (pattern == "std" || pattern == "cmd") && src != gorootSrc {
		continue
	}
	...
}
```

What `SrcDirs` does is return a list of GOROOT + GOPATH workspaces whose src directories exist:

```Go
// SrcDirs returns a list of package source root directories.
// It draws from the current Go root and Go path but omits directories
// that do not exist.
func (ctxt *Context) SrcDirs() []string {
	var all []string
	if ctxt.GOROOT != "" {
		dir := ctxt.joinPath(ctxt.GOROOT, "src")
		if ctxt.isDir(dir) {
			all = append(all, dir)
		}
	}
	for _, p := range ctxt.gopath() {
		dir := ctxt.joinPath(p, "src")
		if ctxt.isDir(dir) {
			all = append(all, dir)
		}
	}
	return all
}
```

Instead of using `SrcDirs` and then trying to skip GOROOT, wouldn't it make sense to just implement a version of `SrcDirs` that doesn't add GOROOT to begin with?

**Comment by shurcooL** [comment]
Ok, I'm going to spend more time on the potential simplifications later. For now, I'll focus on resolving this issue.

I've prototyped and considered various code layouts:

- keeping Go 1.2-1.8 code in root and moving Go 1.9 code to root
- keeping Go 1.2-1.8 code in root and having Go 1.9 code in `internal/load` (as it is [upstream](https://godoc.org/cmd/go/internal/load)).
- moving Go 1.2-1.8 code to `internal/load` and having Go 1.9 code in `internal/load`

It seems to me that the best option is to keep 1.2-1.8 code in root (where it is now), and start having the 1.9 code in `internal/load`. The other options looked worse.

This way, the diff of Go 1.9 code against upstream will be quite small, so it'll be easiest to keep it up to date and make changes in the future. The 1.2-1.8 code will remain unchanged and won't interfere.

For anyone who's interested, this is the diff of the functionality (once flattened) between 1.8 and 1.9 (ignoring the differences to find GOROOT):

<details><summary><strong>diff</strong></summary><br>

```diff
diff --git a/match.go b/match.go
index e9209b7..84e60db 100644
--- a/match.go
+++ b/match.go
@@ -45,17 +45,73 @@ import (
 // name matches pattern. Pattern is a limited glob
 // pattern in which '...' means 'any string' and there
 // is no other special syntax.
+// Unfortunately, there are two special cases. Quoting "go help packages":
+//
+// First, /... at the end of the pattern can match an empty string,
+// so that net/... matches both net and packages in its subdirectories, like net/http.
+// Second, any slash-separted pattern element containing a wildcard never
+// participates in a match of the "vendor" element in the path of a vendored
+// package, so that ./... does not match packages in subdirectories of
+// ./vendor or ./mycode/vendor, but ./vendor/... and ./mycode/vendor/... do.
+// Note, however, that a directory named vendor that itself contains code
+// is not a vendored package: cmd/vendor would be a command named vendor,
+// and the pattern cmd/... matches it.
 func matchPattern(pattern string) func(name string) bool {
+	// Convert pattern to regular expression.
+	// The strategy for the trailing /... is to nest it in an explicit ? expression.
+	// The strategy for the vendor exclusion is to change the unmatchable
+	// vendor strings to a disallowed code point (vendorChar) and to use
+	// "(anything but that codepoint)*" as the implementation of the ... wildcard.
+	// This is a bit complicated but the obvious alternative,
+	// namely a hand-written search like in most shell glob matchers,
+	// is too easy to make accidentally exponential.
+	// Using package regexp guarantees linear-time matching.
+
+	const vendorChar = "\x00"
+
+	if strings.Contains(pattern, vendorChar) {
+		return func(name string) bool { return false }
+	}
+
 	re := regexp.QuoteMeta(pattern)
-	re = strings.Replace(re, `\.\.\.`, `.*`, -1)
-	// Special case: foo/... matches foo too.
-	if strings.HasSuffix(re, `/.*`) {
-		re = re[:len(re)-len(`/.*`)] + `(/.*)?`
+	re = replaceVendor(re, vendorChar)
+	switch {
+	case strings.HasSuffix(re, `/`+vendorChar+`/\.\.\.`):
+		re = strings.TrimSuffix(re, `/`+vendorChar+`/\.\.\.`) + `(/vendor|/` + vendorChar + `/\.\.\.)`
+	case re == vendorChar+`/\.\.\.`:
+		re = `(/vendor|/` + vendorChar + `/\.\.\.)`
+	case strings.HasSuffix(re, `/\.\.\.`):
+		re = strings.TrimSuffix(re, `/\.\.\.`) + `(/\.\.\.)?`
 	}
+	re = strings.Replace(re, `\.\.\.`, `[^`+vendorChar+`]*`, -1)
+
 	reg := regexp.MustCompile(`^` + re + `$`)
-	return reg.MatchString
+
+	return func(name string) bool {
+		if strings.Contains(name, vendorChar) {
+			return false
+		}
+		return reg.MatchString(replaceVendor(name, vendorChar))
+	}
+}
+
+// replaceVendor returns the result of replacing
+// non-trailing vendor path elements in x with repl.
+func replaceVendor(x, repl string) string {
+	if !strings.Contains(x, "vendor") {
+		return x
+	}
+	elem := strings.Split(x, "/")
+	for i := 0; i < len(elem)-1; i++ {
+		if elem[i] == "vendor" {
+			elem[i] = repl
+		}
+	}
+	return strings.Join(elem, "/")
 }
 
+// matchPackages returns a list of package paths matching pattern
+// (see go help packages for pattern syntax).
 func (c *Context) matchPackages(pattern string) []string {
 	match := func(string) bool { return true }
 	treeCanMatch := func(string) bool { return true }
@@ -82,25 +138,39 @@ func (c *Context) matchPackages(pattern string) []string {
 			root += "cmd" + string(filepath.Separator)
 		}
 		filepath.Walk(root, func(path string, fi os.FileInfo, err error) error {
-			if err != nil || !fi.IsDir() || path == src {
+			if err != nil || path == src {
 				return nil
 			}
 
+			want := true
 			// Avoid .foo, _foo, and testdata directory trees.
 			_, elem := filepath.Split(path)
 			if strings.HasPrefix(elem, ".") || strings.HasPrefix(elem, "_") || elem == "testdata" {
-				return filepath.SkipDir
+				want = false
 			}
 
 			name := filepath.ToSlash(path[len(src):])
 			if pattern == "std" && (!isStandardImportPath(name) || name == "cmd") {
 				// The name "std" is only the standard library.
 				// If the name is cmd, it's the root of the command tree.
-				return filepath.SkipDir
+				want = false
 			}
 			if !treeCanMatch(name) {
+				want = false
+			}
+
+			if !fi.IsDir() {
+				if fi.Mode()&os.ModeSymlink != 0 && want {
+					if target, err := os.Stat(path); err == nil && target.IsDir() {
+						fmt.Fprintf(os.Stderr, "warning: ignoring symlink %s\n", path)
+					}
+				}
+				return nil
+			}
+			if !want {
 				return filepath.SkipDir
 			}
+
 			if have[name] {
 				return nil
 			}
@@ -108,12 +178,21 @@ func (c *Context) matchPackages(pattern string) []string {
 			if !match(name) {
 				return nil
 			}
-			_, err = c.BuildContext.ImportDir(path, 0)
+			pkg, err := cfg.BuildContext.ImportDir(path, 0)
 			if err != nil {
 				if _, noGo := err.(*build.NoGoError); noGo {
 					return nil
 				}
 			}
+
+			// If we are expanding "cmd", skip main
+			// packages under cmd/vendor. At least as of
+			// March, 2017, there is one there for the
+			// vendored pprof tool.
+			if pattern == "cmd" && strings.HasPrefix(pkg.ImportPath, "cmd/vendor") && pkg.Name == "main" {
+				return nil
+			}
+
 			pkgs = append(pkgs, name)
 			return nil
 		})
@@ -195,6 +274,9 @@ func (c *Context) allPackagesInFS(pattern string) []string {
 	return pkgs
 }
 
+// matchPackagesInFS returns a list of package paths matching pattern,
+// which must begin with ./ or ../
+// (see go help packages for pattern syntax).
 func (c *Context) matchPackagesInFS(pattern string) []string {
 	// Find directory to begin the scan.
 	// Could be smarter but this one optimization
@@ -260,7 +342,7 @@ func (c *Context) matchPackagesInFS(pattern string) []string {
 	return pkgs
 }
 
-// isMetaPackage checks if name is a reserved package name that expands to multiple packages
+// isMetaPackage checks if name is a reserved package name that expands to multiple packages.
 func isMetaPackage(name string) bool {
 	return name == "std" || name == "cmd" || name == "all"
 }
```
</details><br>

I'm going to backport the documentation differences...

And the rest of the code will be a copy of `cmd/go/internal/load` package of Go 1.9, with the neccessary modifications to pass `build.Context` from `gotool.Context` in a concurrency safe manner.

Instead of getting the values for build context and GOROOT/src directory from `cmd/go/internal/cfg` package (or copy thereof), which would not be safe for concurrent use, I instead create a `Context` type that allows passing in those values. This is very similar to what we did in `gotool` itself for previous versions.

The final diff of the copied `./internal/load` against the upstream `cmd/go/internal/load`, ignoring functions I did not copy because they're not needed, is:

```diff
--- /usr/local/go/src/cmd/go/internal/load/search.go	2017-08-24 17:50:22.000000000 -0400
+++ ./internal/load/search.go	2017-08-27 20:50:48.000000000 -0400
@@ -2,10 +2,11 @@
 // Use of this source code is governed by a BSD-style
 // license that can be found in the LICENSE file.
 
+// +build go1.9
+
 package load
 
 import (
-	"cmd/go/internal/cfg"
 	"fmt"
 	"go/build"
 	"log"
@@ -16,12 +17,23 @@
 	"strings"
 )
 
+// Context provides values that are usually coming from cmd/go/internal/cfg package.
+type Context struct {
+	// Build context to use.
+	BuildContext build.Context
+
+	// GOROOTsrc is the location of the src directory in GOROOT.
+	// At this time, it's used only in in MatchPackages to skip
+	// GOOROOT/src entry from BuildContext.SrcDirs output.
+	GOROOTsrc string
+}
+
 // allPackages returns all the packages that can be found
 // under the $GOPATH directories and $GOROOT matching pattern.
 // The pattern is either "all" (all packages), "std" (standard packages),
 // "cmd" (standard commands), or a path including "...".
-func allPackages(pattern string) []string {
-	pkgs := MatchPackages(pattern)
+func (c *Context) allPackages(pattern string) []string {
+	pkgs := c.MatchPackages(pattern)
 	if len(pkgs) == 0 {
 		fmt.Fprintf(os.Stderr, "warning: %q matched no packages\n", pattern)
 	}
@@ -31,8 +43,8 @@
 // allPackagesInFS is like allPackages but is passed a pattern
 // beginning ./ or ../, meaning it should scan the tree rooted
 // at the given directory. There are ... in the pattern too.
-func allPackagesInFS(pattern string) []string {
-	pkgs := MatchPackagesInFS(pattern)
+func (c *Context) allPackagesInFS(pattern string) []string {
+	pkgs := c.MatchPackagesInFS(pattern)
 	if len(pkgs) == 0 {
 		fmt.Fprintf(os.Stderr, "warning: %q matched no packages\n", pattern)
 	}
@@ -41,7 +53,7 @@
 
 // MatchPackages returns a list of package paths matching pattern
 // (see go help packages for pattern syntax).
-func MatchPackages(pattern string) []string {
+func (c *Context) MatchPackages(pattern string) []string {
 	match := func(string) bool { return true }
 	treeCanMatch := func(string) bool { return true }
 	if !IsMetaPackage(pattern) {
@@ -52,13 +64,13 @@
 	have := map[string]bool{
 		"builtin": true, // ignore pseudo-package that exists only for documentation
 	}
-	if !cfg.BuildContext.CgoEnabled {
+	if !c.BuildContext.CgoEnabled {
 		have["runtime/cgo"] = true // ignore during walk
 	}
 	var pkgs []string
 
-	for _, src := range cfg.BuildContext.SrcDirs() {
-		if (pattern == "std" || pattern == "cmd") && src != cfg.GOROOTsrc {
+	for _, src := range c.BuildContext.SrcDirs() {
+		if (pattern == "std" || pattern == "cmd") && src != c.GOROOTsrc {
 			continue
 		}
 		src = filepath.Clean(src) + string(filepath.Separator)
@@ -107,7 +119,7 @@
 			if !match(name) {
 				return nil
 			}
-			pkg, err := cfg.BuildContext.ImportDir(path, 0)
+			pkg, err := c.BuildContext.ImportDir(path, 0)
 			if err != nil {
 				if _, noGo := err.(*build.NoGoError); noGo {
 					return nil
@@ -132,7 +144,7 @@
 // MatchPackagesInFS returns a list of package paths matching pattern,
 // which must begin with ./ or ../
 // (see go help packages for pattern syntax).
-func MatchPackagesInFS(pattern string) []string {
+func (c *Context) MatchPackagesInFS(pattern string) []string {
 	// Find directory to begin the scan.
 	// Could be smarter but this one optimization
 	// is enough for now, since ... is usually at the
@@ -185,7 +197,7 @@
 		// as not matching the pattern. Go 1.5 and earlier skipped, but that
 		// behavior means people miss serious mistakes.
 		// See golang.org/issue/11407.
-		if p, err := cfg.BuildContext.ImportDir(path, 0); err != nil && (p == nil || len(p.InvalidGoFiles) == 0) {
+		if p, err := c.BuildContext.ImportDir(path, 0); err != nil && (p == nil || len(p.InvalidGoFiles) == 0) {
 			if _, noGo := err.(*build.NoGoError); !noGo {
 				log.Print(err)
 			}
@@ -282,15 +294,15 @@
 }
 
 // ImportPaths returns the import paths to use for the given command line.
-func ImportPaths(args []string) []string {
-	args = ImportPathsNoDotExpansion(args)
+func (c *Context) ImportPaths(args []string) []string {
+	args = c.ImportPathsNoDotExpansion(args)
 	var out []string
 	for _, a := range args {
 		if strings.Contains(a, "...") {
 			if build.IsLocalImport(a) {
-				out = append(out, allPackagesInFS(a)...)
+				out = append(out, c.allPackagesInFS(a)...)
 			} else {
-				out = append(out, allPackages(a)...)
+				out = append(out, c.allPackages(a)...)
 			}
 			continue
 		}
@@ -301,7 +313,7 @@
 
 // ImportPathsNoDotExpansion returns the import paths to use for the given
 // command line, but it does no ... expansion.
-func ImportPathsNoDotExpansion(args []string) []string {
+func (c *Context) ImportPathsNoDotExpansion(args []string) []string {
 	if len(args) == 0 {
 		return []string{"."}
 	}
@@ -324,7 +336,7 @@
 			a = path.Clean(a)
 		}
 		if IsMetaPackage(a) {
-			out = append(out, allPackages(a)...)
+			out = append(out, c.allPackages(a)...)
 			continue
 		}
 		out = append(out, a)
```

**Comment by shurcooL** [comment]
Created PR #17 that'll resolve this issue. Please read its description and then review.
