### ISSUE TITLE
Add a way to supply go/build.ImportMode

### ISSUE THREAD

**Issue by mvdan** [kisielk/gotool#18]
For example, say that one wanted to use gotool, but with `go/build.FindOnly`. This could be used to expand `foo/...` while including directories that have no Go files. `IgnoreVendor` could be useful too.

There is no reason that I can think of not to allow this. It could easily be added to `gotool.Context`, as a field like `ImportMode`. For the 99% of cases that one doesn't need to change the default, it won't cause any trouble or breakage.

Happy to submit a pull request if this seems like a good idea.

**Comment by kisielk** [comment]
I don't think adding an `ImportMode` field really makes sense since the package doesn't actually do any importing or building, it just returns paths. I'm not really sure I understand how the behaviour with `FindOnly` would differ from how it works now? Do you have a more concrete example of how it could be used?

If they're deemed to be useful, we could just add `FindOnly` and `IgnoreVendor` boolean flags on `gotool.Context`.

**Comment by mvdan** [comment]
Perhaps you're right - most of the modes won't be particularly useful. Exposing specific features via bools works for me too.

> I'm not really sure I understand how the behaviour with FindOnly would differ from how it works now?

To get a bit more specific - for an experiment of mine, I've defined something called "gunk packages". They're like Go packages, with Go files in them, but using the `.gunk` extension to make sure they're not mistaken for regular Go code.

I still parse them via `go/parser` and type-check them, as they're still valid Go programs. That all works as usual.

The only difference is when `go/build` is involved - because it requires that a Go package have at least one Go file. If not, it gives `NoGoError`. That's what I use `build.FindOnly` for - it makes it so that finding a package succeeds even if there are no Go files in that directory. I do my filtering of what I consider to be an empty package later.

As an example:

```
func main() {
        fmt.Println(gotool.DefaultContext.ImportPaths(os.Args[1:]))
}
```

And this tree:

```
 $ find .
.
./regular
./regular/f.go
./empty
./others
./others/other.ext
```

The current `gotool` will do:

```
 $ go run ~/gt.go ./...
[./regular]
```

One that is patched to replace `ImportDir(path, 0)` with `ImportDir(path, build.FindOnly)` will do:

```
 $ go run ~/gt.go ./...
[./. ./empty ./others ./regular]
```

**Comment by shurcooL** [comment]
I really think the best solution here is for you to fork `gotool` and modify your copy as you wish for the needs of your experiment. These options don't make sense in the context of the primary purpose of `gotool`:

> Package gotool contains utility functions used to implement the standard "cmd/go" tool, provided as a convenience to developers who want to write tools with similar semantics.

Most importantly, a helpful property of the current code is that it involves minimal difference from upstream code. That makes it easier to maintain it, and to verify it implements same behavior as `cmd/go`. Any further deviations that are unnecessary make that harder.

Having a fork for your needs seems to have all the advantages and none of the disadvantages, so is there a reason you wouldn't want to take that approach?

**Comment by mvdan** [comment]
I thought about a fork - and that was my initial approach. However, as noted above, the change is quite literally two lines (ignoring the extra API).

I realise that this doesn't make a lot of sense when it comes to Go packages. However, following the same logic, `go/build` wouldn't need `FindOnly` either. If `gotool` were part of the standard library, I would definitely expect to be consistent with what `go/build` offers.

And, ultimately, I believe this would be useful for other purposes. I tend to prefer proposing ideas to upstream rather than forking and having to maintain a separate copy, which is why I'm giving this a try.

The point you raise about minimal difference is of course valid, though. How many changes are there between upstream and gotool, besides the API?

**Comment by shurcooL** [comment]
> following the same logic, `go/build` wouldn't need `FindOnly` either. If `gotool` were part of the standard library, I would definitely expect to be consistent with what `go/build` offers.

`go/build` is a much lower level API than `gotool`, hence it has lower level flags. `gotool` is higher level and expected to behave the same as `go list` does; I don't think flags that influence its behavior somehow make much sense.

> How many changes are there between upstream and gotool, besides the API?

Aside from propagating and using [`Context.BuildContext`](https://godoc.org/github.com/kisielk/gotool#Context.BuildContext), none.

Just to summarize and clarify, the reason I'm not convinced this would make a good addition here is because you have a custom need that has no well defined specification, and the entire purpose of `gotool` is to exist to expose well defined existing behavior of `go list` to [Go packages that want that](https://godoc.org/github.com/kisielk/gotool?importers).

**Comment by mvdan** [comment]
> custom need that has no well defined specification

I don't think that's true - it's well defined. Find empty Go packages as well as regular Go packages. Or, in other words, include all packages that would normally return `NoGoError` from `go/build`.

However, I still understand your point of view. I knew that this was likely to get rejected on the grounds of "`go list` doesn't have this feature". I think a command-line tool and a library are a bit different though, even if the library is just a copy. My hope is that it would be a bit more versatile than the command-line tool, as long as it makes sense and the changes are minimal.

**Comment by dominikh** [comment]
There are no "empty Go packages". Quoting the Go specification (emphasis mine):

> A package in turn is constructed from **one or more** source files that together declare constants, types, variables and functions belonging to the package and which are accessible in all files of the same package. 

By extension, Go tools know no such thing, either.

**Comment by dominikh** [comment]
And to expand on `go/build`: FindOnly in `go/build` is used to find candidates for packages. The API in `gotool`, however, returns actual packages, in accordance with how the `go` tool behaves.

**Comment by mvdan** [comment]
I know there is no such thing as an empty Go package as per the spec. You could call this "make gotool find candidates for packages" instead, if that would be more appropriate wording.

**Comment by mvdan** [comment]
Given that `go/packages` is becoming a reality, there's even less reason to insist about this :) thanks all for your input.
