### ISSUE TITLE
ImportPath wildcards not working for absolute paths

### ISSUE THREAD

**Issue by jonmcclintock** [kisielk/gotool#19]
ImportPath() wildcards seem to not be working for absolute paths. Here's a quick repro to demonstrate:

```
package main

import (
        "fmt"
        "os"

        "github.com/kisielk/gotool"
)

func main() {
        if len(os.Args) != 2 {
                fmt.Print("Usage: gotool-repro pathspec\n")
                os.Exit(-1)
        }

        paths := gotool.ImportPaths([]string{os.Args[1]})
        fmt.Printf("%d paths found for '%s'\n", len(paths), os.Args[1])
        for _, pkg := range paths {
                fmt.Printf("- %s\n", pkg)
        }
}
```

Compare the output of two runs:

```
(env) jonm@jonm:~/go/src$ gotool-repro/gotool-repro ./... | head -n1
342 paths found for './...'
(env) jonm@jonm:~/go/src$ gotool-repro/gotool-repro `pwd`/... | head -n1
warning: "/home/jonm/go/src/..." matched no packages
0 paths found for '/home/jonm/go/src/...'
```

**Comment by dominikh** [comment]
This matches how the official `go` tool works (unsurprisingly, since the code in this repository is copied from it.)

```
$ go list $(pwd)/...
warning: "/home/dominikh/prj/src/honnef.co/..." matched no packages
```

Since our goal is explicitly to match `go`'s behaviour, this is working as intended. If you want the behaviour changed, you'll have to file the issue upstream.

**Comment by dominikh** [comment]
Note that when I mention filing the issue upstream, I am not implying that there's a chance of it being implemented, only that it'd be the right place for such a request.

Specifically, the `go` tool operates on import paths, which may be "absolute" (e.g. `github.com/example/foo`) or relative (e.g. `./example/foo`). It does not operate on file system paths. C.f. `go list $PWD`
