### ISSUE TITLE
Relative import paths are not resolved to full import paths.

### ISSUE THREAD

**Issue by shurcooL** [kisielk/gotool#5]
For example, if you cd into $GOPATH/src/github.com/gorilla/mux and run:

```bash
go list ../../kisielk/gotool/
```

You get the complete import path `github.com/kisielk/gotool` as output.

However, with the same current-working directory, running:

```Go
gotool.ImportPaths([]string{"../../kisielk/gotool/"})
```

Returns:

```Go
[]string{"../../kisielk/gotool"}
```

It should be `[]string{"github.com/kisielk/gotool"}`.

**Comment by shurcooL** [comment]
This may not be a bug but rather intended behavior.

The reason `go list ../../kisielk/gotool/` prints the full import path is because it calls `build.Import` on the relative import path to get a [`build.Package`](https://godoc.org/go/build#Package) type and prints its `ImportPath` field (which is the full import path).

So, I'm not unsure if this is a bug or intended behavior. Fixing it simply requires to do more work; it's not a bug in the existing code.

The documentation does not specify how relative import paths are handled.

@kisielk, is this a bug or intended behavior?

I am leaning towards intended behavior... If so, is there room to expand the API to provide `FullImportPaths` which is just like `ImpotPaths`, except it also resolves relative import paths to full import paths (if possible) in this package? Or should I place that in another package?

**Comment by shurcooL** [comment]
I've verified this is not a bug in code by running the `func importPaths(args []string) []string` from `cmd/go` (from Go 1.5) code and it has the same behavior, relative import paths are kept as they are (and it doesn't verify that there's an existing package there).

I think this bug can be resolved by updating the documentation. I will make a PR.

**Comment by kisielk** [comment]
The code in gotool is pretty much copied verbatim from the go sources, so it should behave exactly the same.

**Comment by shurcooL** [comment]
We should also document what happens when you give an empty slice of arguments.

It returns `[]string{"."}` in that case.

See https://github.com/mdempsky/maligned/pull/5#discussion_r70171800.
